import csv
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

from homepage import MainWindow

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/grabbericon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 210, 401, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 15, 10, 10)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.label_email = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_email)
        self.label_fname = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_fname.setObjectName("label_fname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_fname)
        self.lineEdit_fname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_fname.setObjectName("lineEdit_fname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fname)
        self.label_lname = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_lname.setObjectName("label_lname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_lname)
        self.lineEdit_lname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_lname.setObjectName("lineEdit_lname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lname)
        self.label_address = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_address.setObjectName("label_address")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_address)
        self.lineEdit_address = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_address)
        self.label_city = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_city.setObjectName("label_city")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.lineEdit_city = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_city)
        self.label_postal = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_postal.setObjectName("label_postal")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_postal)
        self.lineEdit_postal = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_postal.setObjectName("lineEdit_postal")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_postal)
        self.label_phone = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_phone.setObjectName("label_phone")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_phone)
        self.lineEdit_phone = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_phone)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 510, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        #self.pushButton.clicked.connect(self.submitValue)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(30, 470, 291, 23))
        self.checkBox.setObjectName("checkBox")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(140, 0, 191, 151))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Assets/creds.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_register = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_register.setFont(font)
        self.label_register.setObjectName("label_register")
        self.horizontalLayout.addWidget(self.label_register)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(167, 190, 131, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Credentials"))
        self.label_email.setText(_translate("Dialog", "Email"))
        self.label_fname.setText(_translate("Dialog", "First name"))
        self.label_lname.setText(_translate("Dialog", "Last name"))
        self.label_address.setText(_translate("Dialog", "Address"))
        self.label_city.setText(_translate("Dialog", "City"))
        self.label_postal.setText(_translate("Dialog", "Postal Code"))
        self.label_phone.setText(_translate("Dialog", "Phone"))
        self.pushButton.setText(_translate("Dialog", "Submit"))
        self.checkBox.setText(_translate("Dialog", "Receive updates about new features."))
        self.label_register.setText(_translate("Dialog", "CREDENTIALS"))


class MainWindow_Creds(QtWidgets.QMainWindow, Ui_Dialog):
    def __init__(self, parent=None):
        super(MainWindow_Creds, self).__init__(parent)
        self.setupUi(self)
        self.pushButton.clicked.connect(self.submitValue)

    @QtCore.pyqtSlot()
    def submitValue(self):
        email = self.lineEdit_email.text()
        fname = self.lineEdit_fname.text()
        lname = self.lineEdit_lname.text()
        address = self.lineEdit_address.text()
        city = self.lineEdit_city.text()
        postal = self.lineEdit_postal.text()
        phone = self.lineEdit_phone.text()
        if(email == "" or fname == "" or lname == "" or address == "" or city == "" or postal == "" or phone == ""):
            QtWidgets.QMessageBox.critical(self, 'Grabber Alert', "Fields cant be left empty !!", QtWidgets.QMessageBox.Ok, QtWidgets.QMessageBox.Ok)
        else:
            with open('/home/hakanohi/Projects/Grabber/Engine/checkoutInfo.csv', 'w') as f:
                w = csv.writer(f)
                w.writerow([email, fname, lname, address, city, postal, phone])
            self.homePopUp()
            self.close()

    def homePopUp(self):
        self.home = MainWindow()
        self.home.show()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = MainWindow_Creds()
    Dialog.show()
    sys.exit(app.exec_())
